/*
dhtmlxScheduler v.4.2.0 Professional

This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){e.config.container_autoresize=!0,e.config.month_day_min_height=90;var t=e._pre_render_events;e._pre_render_events=function(i,s){if(!e.config.container_autoresize)return t.apply(this,arguments);var a=this.xy.bar_height,n=this._colsS.heights,r=this._colsS.heights=[0,0,0,0,0,0,0],d=this._els.dhx_cal_data[0];if(i=this._table_view?this._pre_render_events_table(i,s):this._pre_render_events_line(i,s),this._table_view)if(s)this._colsS.heights=n;else{var o=d.firstChild;
if(o.rows){for(var l=0;l<o.rows.length;l++){if(r[l]++,r[l]*a>this._colsS.height-this.xy.month_head_height){var h=o.rows[l].cells,_=this._colsS.height-this.xy.month_head_height;1*this.config.max_month_events!==this.config.max_month_events||r[l]<=this.config.max_month_events?_=r[l]*a:(this.config.max_month_events+1)*a>this._colsS.height-this.xy.month_head_height&&(_=(this.config.max_month_events+1)*a);for(var c=0;c<h.length;c++)h[c].childNodes[1].style.height=_+"px";r[l]=(r[l-1]||0)+h[0].offsetHeight
}r[l]=(r[l-1]||0)+o.rows[l].cells[0].offsetHeight}r.unshift(0),o.parentNode.offsetHeight<o.parentNode.scrollHeight&&!o._h_fix}else if(i.length||"visible"!=this._els.dhx_multi_day[0].style.visibility||(r[0]=-1),i.length||-1==r[0]){var u=(o.parentNode.childNodes,(r[0]+1)*a+1+"px");d.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+parseInt(u,10)+"px",d.style.height=this._obj.offsetHeight-parseInt(d.style.top,10)-(this.xy.margin_top||0)+"px";var f=this._els.dhx_multi_day[0];
f.style.height=u,f.style.visibility=-1==r[0]?"hidden":"visible",f=this._els.dhx_multi_day[1],f.style.height=u,f.style.visibility=-1==r[0]?"hidden":"visible",f.className=r[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small",this._dy_shift=(r[0]+1)*a,r[0]=0}}return i};var i=["dhx_cal_navline","dhx_cal_header","dhx_multi_day","dhx_cal_data"],s=function(t){for(var s=0,a=0;a<i.length;a++){var n=i[a],r=e._els[n]?e._els[n][0]:null,d=0;switch(n){case"dhx_cal_navline":case"dhx_cal_header":d=parseInt(r.style.height,10);
break;case"dhx_multi_day":d=r?r.offsetHeight:0,1==d&&(d=0);break;case"dhx_cal_data":d=Math.max(r.offsetHeight-1,r.scrollHeight);var o=e.getState().mode;if("month"==o){if(e.config.month_day_min_height&&!t){var l=r.getElementsByTagName("tr").length;d=l*e.config.month_day_min_height}t&&(r.style.height=d+"px")}if(e.matrix&&e.matrix[o])if(t)d+=2,r.style.height=d+"px";else{d=2;for(var h=e.matrix[o],_=h.y_unit,c=0;c<_.length;c++)d+=_[c].children?h.folder_dy||h.dy:h.dy}("day"==o||"week"==o)&&(d+=2)}s+=d}e._obj.style.height=s+"px",t||e.updateView()
},a=function(){var t=e.getState().mode;s(),(e.matrix&&e.matrix[t]||"month"==t)&&window.setTimeout(function(){s(!0)},1)};e.attachEvent("onViewChange",a),e.attachEvent("onXLE",a),e.attachEvent("onEventChanged",a),e.attachEvent("onEventCreated",a),e.attachEvent("onEventAdded",a),e.attachEvent("onEventDeleted",a),e.attachEvent("onAfterSchedulerResize",a),e.attachEvent("onClearAll",a)}()});
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_container_autoresize.js.map