@isTest
private class TestMetaDataService {
    
    static TestMethod void metadataService(){
        MetadataService.Picklist a = new MetadataService.Picklist();
        MetadataService.AllOrNoneHeader_element ne = new MetadataService.AllOrNoneHeader_element();
        MetadataService.CallOptions_element ce = new MetadataService.CallOptions_element();
        MetadataService.CustomField cf = new MetadataService.CustomField();
        MetadataService.DebuggingHeader_element de = new MetadataService.DebuggingHeader_element();
        MetadataService.DebuggingInfo_element die = new MetadataService.DebuggingInfo_element();
        MetadataService.FilterItem fi = new MetadataService.FilterItem();
        MetadataService.GlobalPicklistValue gpv = new MetadataService.GlobalPicklistValue();
        MetadataService.LogInfo li = new MetadataService.LogInfo();
        MetadataService.LookupFilter lf = new MetadataService.LookupFilter();
        MetadataService.Metadata m = new MetadataService.Metadata();
        MetadataService.MetadataPort mp = new MetadataService.MetadataPort();
        MetadataService.PicklistValue pv = new MetadataService.PicklistValue();
        MetadataService.readCustomFieldResponse_element rcfe = new MetadataService.readCustomFieldResponse_element();
        MetadataService.ReadCustomFieldResult cfr = new MetadataService.ReadCustomFieldResult();
        MetadataService.readMetadata_element rmde = new MetadataService.readMetadata_element();
        MetadataService.readRecordTypeResponse_element rrt = new MetadataService.readRecordTypeResponse_element();
        MetadataService.ReadRecordTypeResult rtr = new MetadataService.ReadRecordTypeResult();
        MetadataService.RecordTypePicklistValue rtv = new MetadataService.RecordTypePicklistValue();
        MetadataService.RecordType rt = new MetadataService.RecordType(); 
        MetadataService.SessionHeader_element she = new MetadataService.SessionHeader_element();
    }
}