/**
 * @FileName: TestSandboxDataCreatorScript
 * @Description: Test class for SandboxDataCreatorScript
 * @Author: Irfan Tarique
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification 
 *  
 *-----------------------------------------------------------  
 **/
@isTest
public class TestSandboxDataCreatorScript{
    static testmethod public void testSandboxDataCreatorScriptRunAll()
    {
        SandboxDataCreatorScript.runAll();
    }
}